### ISSUE TITLE
Um.... how do I use this?

### ISSUE THREAD

**Issue by kontron360** [Lanboost/TModLoader_LansSharedMap#3]
Do I have to move it into a game folder or something?

**Comment by Lanboost** [comment]
> 
> 
> Do I have to move it into a game folder or something?

You should just be able to download it from the TModLoaders mod "store", on there it is called "Lan's Shared Map" searching for shared made me found it. The version is 1y/o but should in "theory" just work fine. 

I just made the code available here for other developers to learn or develop it further
